apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260510-135111-sdxjhrbuyhy6-service
spec:
  selector:
    app: enterprise-system-20260510-135111-sdxjhrbuyhy6
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
